---
- import_playbook: ensure_python.yml
- hosts: all

  roles:
    - user
    - rails-dependencies
    - { role: rvm.ruby,
        tags: ruby,
        become: yes,

        rvm1_rubies: ['ruby-2.5.3'],
        rvm1_install_flags: '--auto-dotfiles',     # Remove --user-install from defaults
        rvm1_install_path: /home/worker/.rvm,         # Set to system location
        rvm1_user: root                            # Need root account to access system location
      }
    - passenger
    - mysql
    - imagemagick
